name: Checkout file
on: push
jobs:
  file1:
    runs-on: ubuntu-latest
    steps:
      - name: Reading file
        uses: actions/checkout@v4
      - name: Printing
        run: cat index.html
        
